#!/bin/bash
 
TESTCASES=( "${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIRecv-Buffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIISend-Count-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/MissingCall-MPIFinalize.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPISend-Rank.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPITest-Status.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIISend-Communicator-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIISend-Communicator-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/MissingCall-MPIRecv.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIISend-Type.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIRecv-Communicator.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPISend-Type-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPISend-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/MisplacedCall-MPIRecv-Deadlock-4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPISend-Communicator-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPISend-Tag-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPITest-Flag.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/MisplacedCall-MPISend.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPISend-Communicator-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPISend-Communicator-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/MisplacedCall-MPIRecv-Deadlock-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgMismatch-MPIRecv-Tag-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIRecv-Type-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPISend-Type-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/MissingCall-MPIWait.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/MissingCall-MPISend-Deadlock.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPISend-Count-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgMismatch-MPIRecv-Tag-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPISend-Buffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgMismatch-MPIIRecv-Tag-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIISend-Communicator-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgMismatch-MPIIrecv-buffer-overlap.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIIRecv-Reqest.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIISend-Buffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPISend-Count-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIRecv-Type-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIISend-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPISend-Tag-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIISend-Count-4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIISend-Request.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIRecv-Count.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIISend-Tag.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIISend-TargetRank.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/ArgError-MPIRecv-Type-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/pt2pt/MisplacedCall-MPIWait.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPITypeContiguous-OldType.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPITypeContiguous-Count.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPITypeCreateStruct-Count-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPITypeVector-NewType.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPISend-Type-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPITypeCreateHVector-Stride.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgMismatch-MPIRecv-Type-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPISend-Type-4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPITypeCreateStruct-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPITypeCreateStruct-Datatype.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgMismatch-MPIRecv-Type-4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPITypeCreateStruct-Displacements-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPITypeCreateStruct-Displacements-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPITypeContiguous-NewType.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPITypeVector-Blocklength.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPITypeVector-OldType.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPITypeVector-Count.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/MissingCall-MPITypeCommit.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/MisplacedCall-MPITypeCommit-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/usertypes/ArgError-MPIRecv-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIReduce-Op-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIReduce-Op-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/MissingCall-MPIReduce-Deadlock.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIReduce-SendBuffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIGather-SendBuffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/MisplacedCall-MPIBarrier-Deadlock-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/MissingCall-MPIGather-Deadlock.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIGather-RecvBuffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIGather-SendCount-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIAllgather-SendCount.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIReduce-Op-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIReduce-Root.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIGather-RecvType.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIReduce-Count.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgMismatch-MPIReduce-Count.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIGather-Dest.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIScatter-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIScatter-Count-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIGather-SendType.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIReduce-Communicator.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgMismatch-MPIReduce-Op.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIReduce-Op-4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIReduce-RecvBuffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIGather-SendCount-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/MissingCall-MPIIBcast.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgMismatch-MPIReduce-root.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/coll/ArgError-MPIGather-RecvCount.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIPut-SizeNotMatching.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIGet-SizeNotMatching.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIGet-buffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/MisplacedCall-MPIWinFence-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIWinCreate-dispUnit.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIPut-count.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/MissingCall-MPIWinCreate.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/MisplacedCall-MPIWinFree-bufferFree.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/MisplacedCall-MPIGet-bufferModification.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIWinFence-assert.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/MisplacedCall-MPIWinLock.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIWinCreate-size.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIPut-type.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIWinCreate-invalidBuffer-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/MissingCall-MPIWinFence-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIWinCreate-OverwriteWin.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIGet-invalidAccess.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIPut-rank.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/MisplacedCall-MPIPut-bufferModification.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIGet-rank.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/MisplacedCall-MPIWinFence-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIGet-type.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIWinCreate-overlap.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIPut-buffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/MissingCall-MPIWinFence-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/ArgError-MPIPut-InvalidAccess.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/MissingCall-MPIFence.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/conflo/rma/MissingCall-MPIWinFence-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/wtime.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/big_count_status.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/large_tag.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/bottom.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/sendrecv.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/bsend5.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/recv_any.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/waittestnull.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/huge_underflow.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/scancel2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/rqfreeb.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/sendall.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/probenull.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/isendirecv.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/bsend2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/srtest.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/inactivereq.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/bsendpending.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/isendself.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/issendselfcancel.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/bsend4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/bsend1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/cancelanysrc.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/huge_dupcomm.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/bsend3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/simple.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/many_isend.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/probe_unexp.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/huge_anysrc.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/patterns.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/manylmt.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/icsend.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/sendrecv3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/rqstatus.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/anyall.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/dtype_send.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/greq1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/bsendalign.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/isendselfprobe.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/rcancel.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/large_type_sendrec.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/longdouble.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/hindexed_block_contents.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/tmatchsize.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/cxx_types.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/typecommit.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/simple_pack_external2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/tresized2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/zero_blklen_vector.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/vecblklen.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/get_elements.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/subarray.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/darray_cyclic.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/zeroblks.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/tfree.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/typefree.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/gaddress.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/datatype/tresized.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/alltoallw1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/icscatterv.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/icalltoallw.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/alltoallv.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/scattern.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/allred4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/alltoallv0.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/allgather_struct.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/neighb_coll.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/icbcast.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/coll8.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/ibarrier.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/allred3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/coll5.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/coll12.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/allredmany.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/exscan.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/icscatter.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/coll7.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/allred2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/opmaxloc.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/icalltoall.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/coll3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/coll13.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/allred5.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/allgather2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/redscatinter.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/reduce.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/bcastzerotype.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/uoplong.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/redscatblk3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/icgather.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/allgatherv2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/allgatherv3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/redscatbkinter.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/coll9.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/iallred.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/redscat3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/icalltoallv.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/opmin.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/red4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/icbarrier.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/op_commutative.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/coll6.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/icreduce.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/coll10.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/coll4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/bcasttest.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/redscat2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/opprod.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/reduce_local.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/coll2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/longuser.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/redscat.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/opminloc.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/nonblocking.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/red3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/exscan2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/gather.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/opsum.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/red_scat_block.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/coll11.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/red_scat_block2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/alltoallw2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/scantst.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/gather2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/alltoallw_zeros.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/alltoall1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/allgather3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/opmax.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/allred6.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/coll/icgatherv.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/test1_dt.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/strided_getacc_indexed_shared.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/test4_am.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/accfence2_am.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/put_base.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/selfrma.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/win_large_shm.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/aint.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/fetchandadd_tree_am.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/rget_unlock.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/atomic_rmw_gacc.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/rmazero.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/strided_acc_subarray.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/acc_pairtype.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/compare_and_swap.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/strided_acc_indexed.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/atomic_rmw_fop.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/test5.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/lockcontention2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/acc_ordering.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/strided_putget_indexed.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/reqops.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/winname.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/nullpscw.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/atomic_get.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/racc_local_comp.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/lockopts.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/locknull.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/strided_acc_onelock.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/test2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/fetch_and_op.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/flush.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/win_shared_query_null.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/strided_get_indexed.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/req_example.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/fence_shm.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/win_info.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/strided_putget_indexed_shared.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/get_acc_local.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/at_complete.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/get_accumulate.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/getgroup.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/acc_loc.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/contig_displ.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/large_small_acc.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/test4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/test3_am.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/put_bottom.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/fetchandadd.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/rput_local_comp.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/test1_am.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/baseattrwin.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/manyrma3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/test3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/accfence2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/test5_am.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/pscw_ordering.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/test2_am.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/win_zero.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/fetchandadd_am.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/lock_nested.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/fetchandadd_tree.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/wincall.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/manyget.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/win_flavors.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/window_creation.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/test1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/get_struct.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/wintest.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/strided_getacc_indexed.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/atomic_rmw_cas.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/rma/mixedsync.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIRecv-Buffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIRecv-Communicator-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgMismatch-MPIISend-Type.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIISend-Rank-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIISend-Count-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/MissingCall-MPIFinalize.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgMismatch-MPIISend-Communicator-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIISend-Tag-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPITest-Status.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIISend-Type-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIISend-Communicator-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIISend-Communicator-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/MissingCall-MPIRecv.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgMismatch-MPIIRecv-Tag-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgMismatch-MPIRecv-Tag-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIISend-Type-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIIRecv-Communicator-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIRecv-Communicator-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPISend-Rank-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIRecv-Count-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPISend-Type-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIISend-Type-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPISend-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/MisplacedCall-MPIRecv-Deadlock-4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIIRecv-Type-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPISend-Communicator-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPISend-Tag-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPITest-Flag.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgMismatch-MPIRecv-Type-7.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIISend-Tag-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/MisplacedCall-MPISend.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIIRecv-Type-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIIRecv-Count-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPISend-Communicator-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/MisplacedCall-MPIRecv-Deadlock-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgMismatch-MPIRecv-Tag-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIRecv-Tag.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIIRecv-Rank-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIIRecv-Communicator-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIRecv-Type-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIISend-Request-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPISend-Type-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIIRecv-Type-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/MisplacedCall-MPIRecv-Deadlock-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgMismatch-MPISend-Communicator-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/MissingCall-MPIWait.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/MissingCall-MPISend-Deadlock.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPISend-Count-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgMismatch-MPIRecv-Tag-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIIRecv-Rank-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPISend-Buffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgMismatch-MPIIRecv-Tag-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgMismatch-MPIIrecv-buffer-overlap.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIIRecv-Request.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIIRecv-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIRecv-Rank-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgMismatch-MPIRecv-Type-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIISend-Buffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPISend-Count-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIRecv-Rank-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPITest-Flag-duplicate.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIRecv-Type-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIIRecv-Buffer-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIISend-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPISend-Rank-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPISend-Tag-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgMismatch-MPIRecv-Type-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgMismatch-MPISend-Communicator-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIIRecv-Tag.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIISend-Rank-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIRecv-Type-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/ArgError-MPIRecv-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/pt2pt/MisplacedCall-MPIWait.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeContiguous-OldType.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeContiguous-Count.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeCreateStruct-Datatype-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeCreateStruct-Count-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeCreateStruct-Count-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgMismatch-MPIRecv-Type-5.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgMismatch-MPIRecv-Type-6.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeVector-NewType.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeCreateStruct-Datatype-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeCreateStruct-Blocklengths.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPISend-Type-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeCreateHVector-Stride.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgMismatch-MPIRecv-Type-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPISend-Type-4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeCreateStruct-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgMismatch-MPIRecv-Type-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgMismatch-MPIRecv-Type-4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeCreateStruct-Displacements-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeCreateStruct-Displacements-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeContiguous-NewType.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeVector-Blocklength.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeVector-OldType.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/ArgError-MPITypeVector-Count.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/MissingCall-MPITypeCommit.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/usertypes/MisplacedCall-MPITypeCommit-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIReduce-Type-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIScatter-Rank.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIReduce-Op-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-Dest-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/MissingCall-MPIReduce-Deadlock.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIReduce-SendBuffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIScatter-Type-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-SendBuffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-Type-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgMismatch-MPIGather-Type-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIAllgather-Count-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-Count-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/MisplacedCall-MPIBarrier-Deadlock-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-Communicator-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/MissingCall-MPIGather-Deadlock.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIAllgather-SendBuffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIAllgather-RecvBuffer-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-Communicator-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIAllgather-RecvBuffer-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIScatter-RecvBuffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIReduce-Op-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIScatter-SendBuffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIReduce-Root.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIAllgather-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIAllgather-Type-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-Count-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIAllgather-Type-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIScatter-Communicator-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgMismatch-MPIGather-Type-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIScatter-Count-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIAllgather-Type-4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIReduce-Communicator-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-Type-4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-RecvBuffer-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-RecvBuffer-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIAllgather-Type-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIAllgather-Count-4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIAllgather-Communicator-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgMismatch-MPIReduce-Count.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-Type-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIScatter-Type-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIAllgather-Communicator-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIScatter-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIReduce-Count-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIScatter-Count-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/MisplacedCall-MPIBarrier-Deadlock-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-Type-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIReduce-Count-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIAllgather-Count-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIScatter-Communicator-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIReduce-Communicator-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIReduce-Type-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIGather-Dest-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgMismatch-MPIReduce-Op.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIReduce-RecvBuffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIReduce-Type-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/MissingCall-MPIIBcast.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIScatter-Type-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIReduce-Count-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgMismatch-MPIReduce-root.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/coll/ArgError-MPIScatter-Count-4.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIPut-SizeNotMatching.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIGet-SizeNotMatching.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIGet-buffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/MisplacedCall-MPIWinFence-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIWinCreate-invalidBuffer-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIWinCreate-dispUnit.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIPut-count.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/MissingCall-MPIWinCreate.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/MisplacedCall-MPIWinFree-bufferFree.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/MisplacedCall-MPIGet-bufferModification.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgMismatch-MPIPut-type.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIWinFence-assert.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/MisplacedCall-MPIWinLock.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgMismatch-MPIGet-type.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIWinCreate-size.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIWinCreate-invalidBuffer-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/MissingCall-MPIWinFence-3.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIWinCreate-OverwriteWin.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIGet-invalidAccess.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIPut-rank.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/MisplacedCall-MPIPut-bufferModification.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIGet-rank.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/MisplacedCall-MPIWinFence-2.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIWinCreate-overlap.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIPut-buffer.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/MissingCall-MPIWinFence-1.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/ArgError-MPIPut-InvalidAccess.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/MissingCall-MPIFence.c
"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/rma/MissingCall-MPIWinFence-2.c )

if [[ $CI_SCORE_TEST == 1 ]]; then
  TESTCASES=( "${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/pt2pt/bottom.c )
fi

PRELOAD_TRACER="${MPI_ARG_TRACER_LIB}"

# Openmpi
export OMPI_CC=clang
export OMPI_CXX=clang++
export MPICC=mpicc
export CORRBENCH_CFLAGS=""
export CPATH=$CPATH:"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/correct/include:"${MPI_CORRBENCH_BASE}"/micro-benches/0-level/openmp
export OMP_NUM_THREADS=1

TIMEOUT_CMD="/usr/bin/timeout -k 30 30"

for THIS_CASE in "${TESTCASES[@]}"; do
  $MPICC $CORRBENCH_CFLAGS -g -O0 "${THIS_CASE}" -lm -o "${THIS_CASE}".exe
  
  LD_PRELOAD="${PRELOAD_TRACER}" $TIMEOUT_CMD mpirun -n 2 "${THIS_CASE}".exe
  rm "${THIS_CASE}".exe
done

 
