
export MPI_ARG_USAGE_BASE=$(cd $(dirname ${BASH_SOURCE:-$0}) && pwd -P)/mpi-arg-usage

export MPI_SCORING_BASE=$(cd $(dirname ${BASH_SOURCE:-$0}) && pwd -P)

export COBE_FILES=$MPI_SCORING_BASE/traces/corrbench-trace

export MBI_FILES=$MPI_SCORING_BASE/traces/mbi-trace

export HPC_DATA_DIR=$MPI_SCORING_BASE/mpi-arg-usage/output

export ENV_NAME=mpi_analysis

